# ArgoCD Blue/Green 배포 TEST

apiVersion: argoproj.io/v1alpha1     # apps/v1 대신 argoproj.io/v1alpha1을 사용한다
kind: Rollout  # Deplyment 대신 Rollout을 사용한다
metadata:
  name: test-rollout-bluegreen
  namespace: test
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: test-rollout-bluegreen
  template:
    metadata:
      labels:
        app: test-rollout-bluegreen
    spec:
      containers:
        - name: rollout-demo
          image: 361848949410.dkr.ecr.ap-northeast-2.amazonaws.com/cicd_test:87
          # image: 361848949410.dkr.ecr.ap-northeast-2.amazonaws.com/cicd_test:88
          ports:
            - containerPort: 3000
          resources: {}
      imagePullSecrets:
        - name: aws
  strategy:
    blueGreen:
      #activeService는 이전의 배포된 Blue 서비스
      activeService: test-rollout-bluegreen-active
      
      #previewService는 새롭게 배포될 Green 서비스
      previewService: test-rollout-bluegreen-preview
      
      #autoPromotioEnabled 옵션은 Blue/Green 배포를 자동으로 진행할 것인지 여부. false 옵션을 사용해 수동으로 지정
      autoPromotionEnabled: false

---
apiVersion: v1
kind: Service
metadata:
  name: test-rollout-bluegreen-active
  namespace: test
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: test-rollout-bluegreen

---
apiVersion: v1
kind: Service
metadata:
  name: test-rollout-bluegreen-preview
  namespace: test
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: test-rollout-bluegreen

